[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.flake8]
max-line-length = 88
exclude = ".git,__pycache__,venv"
ignore = "E501,W503,E722"
