"""first migration

Revision ID: 30efb1b315e3
Revises: 
Create Date: 2023-10-15 13:07:30.278271

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30efb1b315e3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ROLE_APPLICATIONS",
        "role_app_ts_create",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "ROLE_DETAILS",
        "role_description",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sa.String(length=50000),
        existing_nullable=True,
    )
    op.alter_column(
        "ROLE_LISTINGS",
        "role_listing_desc",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sa.String(length=50000),
        existing_nullable=True,
    )
    op.alter_column(
        "ROLE_LISTINGS",
        "role_listing_ts_update",
        existing_type=mysql.DATETIME(),
        nullable=True,
    )
    op.create_foreign_key(
        None,
        "STAFF_REPORTING_OFFICER",
        "STAFF_DETAILS",
        ["staff_id"],
        ["staff_id"],
    )
    op.create_foreign_key(
        None, "STAFF_ROLES", "STAFF_DETAILS", ["staff_id"], ["staff_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "STAFF_ROLES", type_="foreignkey")
    op.drop_constraint(None, "STAFF_REPORTING_OFFICER", type_="foreignkey")
    op.alter_column(
        "ROLE_LISTINGS",
        "role_listing_ts_update",
        existing_type=mysql.DATETIME(),
        nullable=False,
    )
    op.alter_column(
        "ROLE_LISTINGS",
        "role_listing_desc",
        existing_type=sa.String(length=50000),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "ROLE_DETAILS",
        "role_description",
        existing_type=sa.String(length=50000),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "ROLE_APPLICATIONS",
        "role_app_ts_create",
        existing_type=sa.DateTime(),
        type_=mysql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    # ### end Alembic commands ###
