"""auto increment

Revision ID: 990d4de23ccd
Revises: 06b7c9491374
Create Date: 2023-10-15 13:32:37.963447

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "990d4de23ccd"
down_revision: Union[str, None] = "06b7c9491374"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ROLE_DETAILS",
        "role_description",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sa.String(length=50000),
        existing_nullable=True,
    )
    op.alter_column(
        "ROLE_LISTINGS",
        "role_listing_desc",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sa.String(length=50000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ROLE_LISTINGS",
        "role_listing_desc",
        existing_type=sa.String(length=50000),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "ROLE_DETAILS",
        "role_description",
        existing_type=sa.String(length=50000),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
