"""ADD COLS TO ROLE_LISTING

Revision ID: afae9f85e499
Revises: 990d4de23ccd
Create Date: 2023-10-21 15:18:16.449285

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afae9f85e499"
down_revision: Union[str, None] = "990d4de23ccd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ROLE_DETAILS",
        "role_description",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sa.String(length=50000),
        existing_nullable=True,
    )
    op.add_column(
        "ROLE_LISTINGS",
        sa.Column("role_department", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "ROLE_LISTINGS",
        sa.Column("role_location", sa.String(length=50), nullable=True),
    )
    op.alter_column(
        "ROLE_LISTINGS",
        "role_listing_desc",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sa.String(length=50000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ROLE_LISTINGS",
        "role_listing_desc",
        existing_type=sa.String(length=50000),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=True,
    )
    op.drop_column("ROLE_LISTINGS", "role_location")
    op.drop_column("ROLE_LISTINGS", "role_department")
    op.alter_column(
        "ROLE_DETAILS",
        "role_description",
        existing_type=sa.String(length=50000),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
