import type { Metadata } from "next";
import "./globals.scss";

import Sidebar from "@/components/Sidebar";
import { inter } from "@/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "dark bg-background text-foreground")}
      >
        <div className="flex flex-auto">
          <aside>
            <Sidebar />
          </aside>
          <main className="grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
