name: On PR Open

on:
  #everytime a new commit is pushed to PR, this workflow will run
  pull_request:

env:
  NODE_VERSION: "18.x"

# Ensure only a single job or workflow using the same concurrency group will run at a time
# When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress,
# the queued job or workflow will be pending.
concurrency:
  group: ${{ github.ref }}-on-pr-open # The branch or tag ref that triggered the workflow run.

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5
    steps:
      - name: Check if PR title follows conventional commits specs
        if: ${{ !contains(github.event.pull_request.title, '[Snyk]') }}
        uses: amannn/action-semantic-pull-request@v5.1.0
        env:
          # using github token for external/dependabot PR,
          # personal access tokens in secrets will not be accessible in
          # pipeline for external user PRs
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Install OS dependencies
        run: |
          apt-get update
          apt-get -y install xz-utils procps
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          npm i
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Markdown lint
        run: npm run lint:markdown
